---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs3-storage
  #annotations:
    #storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/$K8SPROV
parameters:
  archiveOnDelete: "false"
mountOptions:
- nfsvers=3
- nolock
